server:
  port: 8878
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application: 
    name: 'news-edit-ms'
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/mybatisdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai'
pagehelper:
  helper-dialect: mysql
  reasonable: true

 