eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /news-query/**
      service-id: news-query-ms
    api-b:
      path: /news-edit/**
      service-id: news-edit-ms